export { defineConfig, type Config } from './config.js'
export type { Action, Decision, Rule, RuleResult } from './rule.js'
export { filenameCasing, type Style } from './rules/filename-casing.js'
export { forbidCommandPattern } from './rules/forbid-command-pattern.js'
export { forbidContentPattern } from './rules/forbid-content-pattern.js'
